language:
- node_js
node_js:
- 5.0.0
before_script:
- npm install -g gulp
- yarn
script:
- gulp build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  email: publish@travis.github
  name: "Travis (DevTernity)"
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  slack:
    secure: yB4Tcyg0wpv739xwZktCru4G+sZdq2gv8zz/GdBB6WS2Ggbak+pEOHM6U2BXHQRsGu0uhkf2/2uckAYsrGX1P4jaiZepKwrx5J25tFZbNiYV1jWnTO6fgp44IEN1vNud+PhnrmPTDAoFCbDviGYvKNXbSM2exUAW3SpdDw9rBDwrHgdeYa/Xvz8wNjCYyrl0IowaSJgDSxwoHZWxpqo6ugBS22PngDarRLkw7EwwE8RVTmh9/Tkm0XysXw94Bx+Ld0Qv4jv140x9ArCwEylzcp2398iOwFYrPcehu/HeTQ4V2Eqh48APc+IMiHR8Y6k8VO5oM38QYB/tCwnsaTtWyQC06EqV61yDJet7pczfA2i0uWVz0iUwvXodaZ3nWMGKYG6jOOqGp29HJt76gVXsutkgMe8+ZX8HhtV4nobNasLAvKFRyjCI4u81O+ZCDNB97DThjt5cmt4TJZSvTU2l5TXXl6WWdNtiFK76Vm8q4lud0X6MobDmBanExuE5qsyyfevZybezX9Q4AW+JtG8Tr/7pWCxyFhp77RtgFW8iR/uHcn95REsFBT6ntFxY713I93frwqkXYrd4UGa/1MkpGYF4Xr6Jbk01XoPRC85DutO4D2tPP6aYX3Jr5JNOVPpgT+YOwhouEDMavQkLuxotMgSG2lbtJT3OVJo9t+THAEc=
env:
  global:
    secure: JhBdAQ5dIPCCBX4YrVrNxIWHlHG68+9gCqMxuU55Z6CDuaWXY6iJbrMcrxfqL0QroI6RX26UmC3TTqwCfc5bMyLrj35SA1Ik8hDQyifuDe+Alv2kttnJlzMBnfGQPguYs9eMFtKe6GSaK/pP0yI0hW95z6rD66LyT99H/zRj3AhpaFTUOHFIkA3f60I5Vi8u0KNpT6UGOpXgp3RQ4P9YaHhegHzzvpowYv2T/ojv0MHwF/MMz6Nsk9CX/vs9CJHB99rOj3biipwFxrX/yVW5+JrSKG8sP2bHACNndv7MPZ8JcT6UuToQDlicLmlgudbjy3+dhmsJtjrY45Idj4Ny7ZgGGU1Qwju0Z6YwBiLTgGQ9VpdHYmcxv1oPOdq0xr9zpFVF96I7N8MtQV81BScu7DF/H2oL8t29AkdJ/BI/gR8U+0bDC+5W5Xqzx2+Sn3jS4ibtXa9liMDOTxxkmkBDa0dNcGiMSfQ2ENwMr131kCAs8s3+v6vIp3iAyouZmh19jM73r587emGI7zUh6Fqc3p8iC80KXIgRs9z7P4jdlksQxGgQwiIAvpMrNpDunm8iATXK8svvOTxoA8OaClkmq0P7hWENTfjFzsFxv5qIxPsYUbyK9a2WwmY0ApLxBEQLVBNgCmvZrZ9dNfBX4QrAlBKzIQQnjIG8q2rjG8EhHk0=
