language:
- node_js
node_js:
- 5.0.0
before_script:
- npm install -g gulp
- yarn
script:
- gulp build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  email: publish@travis.github
  name: "Travis (DevTernity)"
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  slack:
    secure: yB4Tcyg0wpv739xwZktCru4G+sZdq2gv8zz/GdBB6WS2Ggbak+pEOHM6U2BXHQRsGu0uhkf2/2uckAYsrGX1P4jaiZepKwrx5J25tFZbNiYV1jWnTO6fgp44IEN1vNud+PhnrmPTDAoFCbDviGYvKNXbSM2exUAW3SpdDw9rBDwrHgdeYa/Xvz8wNjCYyrl0IowaSJgDSxwoHZWxpqo6ugBS22PngDarRLkw7EwwE8RVTmh9/Tkm0XysXw94Bx+Ld0Qv4jv140x9ArCwEylzcp2398iOwFYrPcehu/HeTQ4V2Eqh48APc+IMiHR8Y6k8VO5oM38QYB/tCwnsaTtWyQC06EqV61yDJet7pczfA2i0uWVz0iUwvXodaZ3nWMGKYG6jOOqGp29HJt76gVXsutkgMe8+ZX8HhtV4nobNasLAvKFRyjCI4u81O+ZCDNB97DThjt5cmt4TJZSvTU2l5TXXl6WWdNtiFK76Vm8q4lud0X6MobDmBanExuE5qsyyfevZybezX9Q4AW+JtG8Tr/7pWCxyFhp77RtgFW8iR/uHcn95REsFBT6ntFxY713I93frwqkXYrd4UGa/1MkpGYF4Xr6Jbk01XoPRC85DutO4D2tPP6aYX3Jr5JNOVPpgT+YOwhouEDMavQkLuxotMgSG2lbtJT3OVJo9t+THAEc=
env:
  global:
    secure: p9ux6HJTuLk0yh+mndcS+syoS9tk52bY5o8vxy4P9IMfWo0i9KfUNb+CBBDB+jKG+1OaztbXsgJzCpFy1qIzeSXLkLhiyiqQMSyvfiESiHwi+KjGC2oIzXZ3MuDklOZxpJRZOzifNqu6KliwvQaVRWzcL9w7p7zOUCSiRX4YbqV7/kV7KkCR39OXc5ZpW8Mj4m/oIa1vAE1oKmDQGN+afPqJkDStV7A0SvvsAgHyE85eB/mHxOYoFqZ01IrUiJInE/RZSVFB/+MJvlaFSK7IEAsc1qPmlU0n4ThIzI2hGgfuHQN3/UhEITt5/JjjTDRmh5fPJPfzEzDq5+spANDwTtbvPSHhJf0feHWFULOpV1JV4/Q44U14jPsbNvVEl3PkjSDh6wsVGbq2rBND5lgMR8WE9L7vWcYE24NH3kj7dbWxbRS1AqPhf5rO5671mym/9BfeAZXUS0jrfI+XJhDgCWG3zSGLigPNsLnInIJoQzVKQFQ7JO3KwAcR/NFJ56RUUQcdcavXl3p8EAeG3Upj+bacjYz3aXW4z5rxF29IrJTiB7hMz7v+j2CTdrFn8gOR7E5nJx8czvkLscklS14SPhsb7yvXSeeLs459pDECY4kkNgaCkpEFFtgDYSCEA76syghY6I6WyCI+6Mn4fHXAG6UkZTtAdb3R3WntTWMRfms=
